server:
  port: 8080

# Flight Service Configuration
flight:
  serpapi:
    key: ${FLIGHT_SERPAPI_KEY:}  # Gets value from environment variable FLIGHT_SERPAPI_KEY

# Legacy SerpAPI configuration for backward compatibility  
serpapi:
  key: ${FLIGHT_SERPAPI_KEY:}

# Logging Configuration
logging:
  level:
    com.serpapi.flightmcp: DEBUG
    org.springframework.web: INFO
    org.springframework.ai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Spring AI Configuration
spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:7b  # Using model from application.yml
          temperature: 0.7